# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/sleepstagingidal',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/sleepstagingidal',
                'lib_path': 'sleepstagingidal'},
  'syms': {'sleepstagingidal.data': {'sleepstagingidal.data.get_epochs': ('data_loading.html#get_epochs', 'sleepstagingidal/data.py')}}}