# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/sleepstagingidal',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/sleepstagingidal',
                'lib_path': 'sleepstagingidal'},
  'syms': { 'sleepstagingidal.data': { 'sleepstagingidal.data.get_epochs': ('data_loading.html#get_epochs', 'sleepstagingidal/data.py'),
                                       'sleepstagingidal.data.get_epochs_from_path': ( 'data_loading.html#get_epochs_from_path',
                                                                                       'sleepstagingidal/data.py')},
            'sleepstagingidal.dataa': { 'sleepstagingidal.dataa.get_sleep_stages': ( 'sanity_checking.html#get_sleep_stages',
                                                                                     'sleepstagingidal/dataa.py'),
                                        'sleepstagingidal.dataa.map_events': ( 'sanity_checking.html#map_events',
                                                                               'sleepstagingidal/dataa.py'),
                                        'sleepstagingidal.dataa.swap_dict': ( 'sanity_checking.html#swap_dict',
                                                                              'sleepstagingidal/dataa.py')},
            'sleepstagingidal.feature_extraction': { 'sleepstagingidal.feature_extraction.calculate_bandpower': ( 'feature_extraction.html#calculate_bandpower',
                                                                                                                  'sleepstagingidal/feature_extraction.py')}}}