# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_data_loading.ipynb.

# %% auto 0
__all__ = ['get_epochs']

# %% ../Notebooks/00_data_loading.ipynb 3
import os
from glob import glob
from collections import Counter
from typing import List, Tuple

import numpy as np
import matplotlib.pyplot as plt

import mne
import yasa

# %% ../Notebooks/00_data_loading.ipynb 24
def get_epochs(data: mne.io.edf.edf.RawEDF, # Raw file loaded with `mne.io.read_raw_edf`.
               channels: List[str]=None, # List of channels to keep. If None all the channels are kept.
               ) -> Tuple[mne.epochs.Epochs, float]: # Epochs object and samplign rate of the signal.
    """Extracts labelled epochs from an already loaded raw edf file."""
    sampling_rate = data.info['sfreq']
    events, events_id = mne.events_from_annotations(data, regexp='Sleep stage [A-Z]\d*')

    tmax = 30. - 1. / sampling_rate  # tmax is included
    epochs = mne.Epochs(raw=data, 
                        events=events,
                        event_id=events_id,
                        tmin=0., 
                        tmax=tmax, 
                        baseline=None, 
                        event_repeated='merge',
                        picks=channels)

    epochs.drop_bad()
    return epochs, sampling_rate
